Sultan/cookie banner
Software-For-Love/software-for-love-site pull request #104
Opened 2021-06-26 16:34 UTC by sultanoloyede

@CoderHahs Cookie banner and Google Analytics

2021-06-26 23:24 UTC, CoderHahs approved these changes

2021-06-26 23:25 UTC, CoderHahs requested changes
Privacy policy link does not go to correct page

2021-06-26 23:27 UTC, sultanoloyede commented
I got the new link from Soorya so I’ll make that change and push it to my branch.
________________________________
From: Hrithik Shah ***@***.***>
Sent: Saturday, June 26, 2021 7:26:01 PM
To: Software-For-Love/software-for-love-site ***@***.***>
Cc: sultanoloyede ***@***.***>; Author ***@***.***>
Subject: Re: [Software-For-Love/software-for-love-site] Sultan/cookie banner (#104)


@CoderHahs requested changes on this pull request.

Privacy policy link does not go to correct page

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/Software-For-Love/software-for-love-site/pull/104#pullrequestreview-693365462>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMHAOH2RUEHUU7J7HSC72YDTUZOYTANCNFSM47LP5EZQ>.

2021-06-30 13:54 UTC, Suri111200 commented
@sultanoloyede lmk if you're having any difficulties making the change

2021-06-30 21:00 UTC, CoderHahs approved these changes

2021-06-30 21:02 UTC, CoderHahs approved these changes

2021-06-30 21:02 UTC, merged