Adding the new version of the website with the teams page modified
Software-For-Love/software-for-love-site pull request #135
Opened 2021-08-31 02:44 UTC by jey12345678

2021-08-31 03:02 UTC, Suri111200 requested changes
Please fix Jill's LinkedIn.

2021-08-31 03:02 UTC, Suri111200 commented on src/data/team/Finance-Team/jill-mezenberg.yaml
> +linkedin: "https://www.linkedin.com/in/fletcher-trinier-56288215b/"
Please replace with Jill's LinkedIn-- this is Fletcher's.

2021-08-31 03:16 UTC, Suri111200 requested changes
Please revert package.json

2021-08-31 03:16 UTC, Suri111200 commented on package.json
> +    "gatsby": "^2.22.17",
This change is also not desired and may break the site.

2021-08-31 03:18 UTC, Suri111200 commented
Also @jey12345678 please compress Michael's photo. It's 8.9 MB which is unnecessarily large

2021-08-31 16:16 UTC, Suri111200 approved these changes
LGTM. @AvaneeshM please review as well.

2021-09-02 15:16 UTC, Suri111200 requested changes
@AvaneeshM @jey12345678 please investigate failing tests-- not sure why that's the case. We can talk about this later if you would like

2021-09-02 15:42 UTC, AvaneeshM approved these changes

2021-09-02 15:42 UTC, merged