Updating index.md
Software-For-Love/software-for-love-site pull request #136
Opened 2021-09-06 21:28 UTC by NutanNimkar

added a new two new titles and services offered

2021-09-11 15:32 UTC, AvaneeshM approved these changes

2021-09-27 03:21 UTC, Suri111200 approved these changes

2021-10-04 02:12 UTC, Suri111200 requested changes
Just noticed that the content here is just copied over from another section. Going to get the marketing team to rewrite it.

2021-11-21 15:51 UTC, Suri111200 approved these changes

2021-11-21 15:51 UTC, merged