Add projects section to homepage
Software-For-Love/software-for-love-site pull request #259
Opened 2022-09-03 15:45 UTC by alexander-azizi-martin

This PR:
- adds the project section to the homepage
- changes background color of sections on the homepage
- fixes spacing issues on the homepage

2022-09-09 17:45 UTC, kandloic commented on src/pages/index.md
> +            redirect: http://localhost:8888/projects
should the redirect not be: `/projects`?

2022-09-09 17:46 UTC, kandloic commented on src/pages/index.md
> +            redirect: http://localhost:8888/projects
see comment above

2022-09-09 17:50 UTC, kandloic commented on src/pages/index.md
> +            redirect: http://localhost:8888/projects
see comment above

2022-09-09 17:51 UTC, kandloic commented on src/pages/index.md
> +          url: http://localhost:8888/
think url should just be: `/`

2022-09-09 17:52 UTC, kandloic commented on src/pages/index.md
> +            redirect: http://localhost:8888/projects
read more on absolute vs relative urls: https://docs.microsoft.com/en-us/sql/ado/guide/data/absolute-and-relative-urls?view=sql-server-ver16

2022-09-09 18:19 UTC, kandloic requested changes
Looks good overall. Left a few comments that should be addressed (:

2023-02-24 22:10 UTC, snhumphr commented
This branch/pull request is now obsolete, the projects section update has now been merged into  https://github.com/Software-For-Love/software-for-love-site/tree/SFLW-65-section-1-home-page-redesign.

2023-02-24 22:10 UTC, closed without merging